# name: Next.js Build Check
# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]
# env:
#   FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
# jobs:
#   build:
#     if: contains(github.event.head_commit.message, 'deploy_Production')
#     runs-on: ubuntu-latest
#     concurrency:
#       group: build-nextjs
#       cancel-in-progress: true
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 24
#           cache: "npm"

#       - name: Install dependencies
#         run: npm ci

#       - name: Create .env file
#         run: |
#           echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
#           echo "SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}" >> .env
#           echo "SESSION_COOKIE_NAME=${{ secrets.SESSION_COOKIE_NAME }}" >> .env
#           echo "SESSION_MAX_AGE_DAYS=${{ secrets.SESSION_MAX_AGE_DAYS }}" >> .env

#       - name: Build Next.js app
#         run: npm run build
